### ISSUE TITLE
Versioning of terms - discussion Sept 2022

### ISSUE THREAD

**Issue by henkvancann** [essif-lab/framework#131]
Henk van Cann:

  [10:28 AM](https://keriworld.slack.com/archives/D03RLLPT52T/p1662107316337279)
Daniel, I have a question about **keeping in sync with changes to the ToIP glossary**. I store terms under their name (e.g. ‘issuance-event’) in one central database, where I intend to generate a documentation site and sidebar menus from. I have attached a unique identifier to a term (not yet used by the way).
A key situation would be the change of the name of term.
My question is this one: could I get a periodic update of ToIP terms (acdc, but also the other ToIP glossary wikis) that have changed the name (old name-new name) of the term, because those ones are going to be dead links if I don’t regularly process them at my receiving end.
Example : ‘issuance-event’ changes for some reason not relevant to ‘issuer-event’.
Proposed follow-up: Github Actions “knows” this and reports in intervals (once per week, per month) to those e-mail addresses that have subscribed.
If an editor of a glossary changes the name of term (but keeps the concept/explanation more or less the same), then he / she  should alter the text of the old term in a way that is backward compatible, either:
a) the old term gets a new meaning plus a forwarder to new name (with the old concept text).
b) the old term gets a forwarder (old name url -> new name url) which becomes obsolete over time (edited) 
white_check_mark
eyes
raised_hands

Daniel Hardman
  [10:42 AM](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108120632989)
Each repo keeps a record of github actions that it run, so you can see whether/when the glossary has been regenerated by looking at that log: https://github.com/trustoverip/acdc/actions
Even better is to use the github compare function. Here is a URL that shows everything that has changed in the glossary in the past 7 days:
https://github.com/trustoverip/acdc/compare/gh_pages%40%7B7day%7D...gh_pages
You can change the "7day" part to get other durations.
Does this accomplish what you want?
[10:44](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108255877719)
Here is more info about how to use the compare function: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits

Henk van Cann
  [10:44 AM](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108297899549)
I’ll check it out, sounds good. However, I am more concerned about the human intervention (the governance aspect)
Idealistic someone (including myself!) who changes names has a sort of a duty?
Example a)
issuance-event
## Definition
<new meaning>
## Former Concept
[Issuer-event](issuer-event)
Example b)
<could be done automatically by Github Actions>

Daniel Hardman
  [10:46 AM](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108379948459)
I see. Yes, that's a bit different. Yes, right now the plan is that this is the job of the human curator. Adding a feature to a github action to do it automatically would be cool, but it's not something I can work on at the present.

Henk van Cann
  [10:48 AM](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108537837769)
I need to study Github Actions more (but also focussed on other stuff). It’s good to sync about this very specific situation, It happens quite often in the keri team: acronyms and names change.
[10:49](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108566871199)
we need to keep track in some way

Daniel Hardman
  [10:50 AM](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108614001299)
**I think that instead of renaming something, we should deprecate the old thing and then add a new thing, and cross-link them (so that the old term is still searchable, but is marked as deprecated, and so the new term contains a note that it has replaced the old term). This is typically how professional terminologists do it. (edited)** 

Henk van Cann
  [10:50 AM](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108650679529)
**that sounds great, yes better than my approach**
[10:51](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108711477189)
This however, works only if the old name does not get a new meaning
[10:52](https://keriworld.slack.com/archives/D03RLLPT52T/p1662108753590019)
But anyways, let’s say, it’s on our agenda :)
:+1:

**Comment by sih** [comment]
> I think that instead of renaming something, we should deprecate the old thing and then add a new thing, and cross-link them (so that the old term is still searchable, but is marked as deprecated, and so the new term contains a note that it has replaced the old term). This is typically how professional terminologists do it. (edited)

+1 to this and FWIW this is also the way that append-only architectures work which both ensure there is no data loss and provide the ability to answer point-in-time questions, e.g. what was the definition when this version was being used. Both of these seem to be valuable features in terms definitions
