### ISSUE TITLE
Generation of website is crashing, and needs to be fixed

### ISSUE THREAD

**Issue by RieksJ** [essif-lab/framework#183]
@Ca5e : I inadvertently did something wrong as I attempted to clean up the essif-lab repo - it no longer builds like it should.

I think the problem is that I (locally) dit an `npm install` to ensure I would locally get the updated TEv2 tool stuff. While I was surprised it took quite some time (locally), I didn't think much of it as `npm start` worked (locally). However, since then the generation in github no longer worked. Perhaps the npm-lock-something file is the culprit?

Can you find and fix the problem?

**Comment by Ca5e** [comment]
It works again after removing the committed `package-lock.json`, I've added this to the `.gitignore` file for now so we don't have to worry about committing it again.
When we tackle updating to Docusaurus 3.0 (which was quite easy, we only have to made sure we're using valid MDX 3 formatting), I believe the underlying react module error (see below) would be fixed and we could commit a `package-lock.json` again.

```
Module not found: Error: Can't resolve 'react-loadable' in '/home/runner/work/framework/framework/node_modules/@docusaurus/core/lib/client/exports'
```

**Comment by RieksJ** [comment]
@Ca5e : ik heb hem alweer gemold, deze keer wellicht door het mergen van een of andere automatisch gegenereerde PR. Kun je dat nog een keer fixen?

**Comment by Ca5e** [comment]
Blijkbaar heeft de dependabot gisteren de Docusaurus 3.0 update automatisch uitgevoerd. Ik weet niet zeker hoe die bot werkt, en geloof ook niet dat ik die instellingen kan bijwerken in deze repo. De errors komen doordat de react versie die we nu gebruiken niet nieuw genoeg is voor het nieuwe Docusaurus.
De [commit](https://github.com/essif-lab/framework/commit/c17f9f7cea7b50d5bcecdde3ae2c8cce0ff86ef6) van de bot kan ik niet zomaar ongedaan maken, en het zou kunnen dat de bot deze wijziging/update daarna gewoon opnieuw uitvoert.
Dus, of even kijken of we die bot zich kunnen laten gedragen, of ik kan de upgrade naar 3.0 (zoals ik die in [mijn fork](https://github.com/Ca5e/framework/tree/docusaurus-3.0) al heb geprobeerd) uitvoeren (wel handig om alsnog even de instellingen van de bot te controleren).

**Comment by RieksJ** [comment]
maakt me niet uit zolang het maar werkt...

**Comment by Ca5e** [comment]
Upgrade to 3.1 completed.
